# Generated by Django 4.1 on 2022-08-19 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('date_listed', models.DateField(default=datetime.date.today)),
                ('date_applied', models.DateField(default=datetime.date.today)),
                ('result', models.CharField(max_length=20)),
                ('contacts', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
