# Generated by Django 4.1 on 2022-08-16 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('date_listed', models.DateField()),
                ('date_applied', models.DateField()),
                ('follow_up', models.BooleanField()),
                ('result', models.CharField(max_length=20)),
                ('contacts', models.CharField(max_length=200)),
                ('applicationlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.applicationlist')),
            ],
        ),
    ]
